### ISSUE TITLE
test_score is NaN during training

### ISSUE THREAD

**Issue by licaizi** [IssamLaradji/covid19_weak_supervision#2]
Hi, thanks for your code. I am trying to reproduce your experimental results, and when running trainval.py on dataset v1, I found the "test_score" is always "NaN" after epoch 0. I conduct experiments  on ubuntu16.04 with pytorch 1.4. Looking forward to you reply, thanks a lot
![image](https://user-images.githubusercontent.com/6143725/89499646-ef981380-d7f2-11ea-9a15-379a131a5a7e.png)

**Comment by licaizi** [comment]
Another warning is "weights not avaliable...", I don't know if it is a problem

**Comment by IssamLaradji** [comment]
The `NaN` is there because the `test_score` is not computed at every epoch. It is only computed in epochs when the validation score is higher than the best obtained validation score. The last test score in the printed dataframe is the one that represents the true test score. The `NaN` needs to be changed to something more informative!

Since your results are saved in `/home/licaizi/Projects/COVID/covid19_weak_supervision/save_dirs'
`,  you can visualize them with the following script,

```
from haven import haven_results as hr
from haven import haven_utils as hu
savedir_base = '/home/licaizi/Projects/COVID/covid19_weak_supervision/save_dirs'


rm = hr.ResultManager(exp_list=None, 
                      savedir_base=savedir_base, 
                      verbose=0
                     )
y_metrics = ['train_loss', 'test_score']
legend_list = ['model.loss']
title_list = ['dataset.name']

rm.get_plot_all(y_metric_list=y_metrics, 
                           x_metric='epoch', title_list=title_list, 
                          figsize=(10*len(y_metrics), 5), 
                          legend_list=legend_list)
```

**Comment by licaizi** [comment]
@IssamLaradji Have you tried cross-validation? is there exists data bias to validate models only by 5 slices?

**Comment by IssamLaradji** [comment]
I haven't. But I would be surprised if the results are not consistent with cross-validation.

It is a good experiment to try though, but it will take way longer to complete.

**Comment by licaizi** [comment]
Thanks for your reply, the code helps me a lot!
